/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import dao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author linco
 */
public class Vacinas_Tela_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Vacinas
     */
    public Vacinas_Tela_Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        campoLaboratorio = new javax.swing.JTextField();
        campoValidade = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataVal = new javax.swing.text.MaskFormatter("##/##/####");
            campoValidade = new javax.swing.JFormattedTextField(dataVal);
        } catch (Exception e) {
        }
        campoLote = new javax.swing.JTextField();
        campoObs = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Vacinas");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(682, 293));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel2.setText("Descrição");

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel3.setText("Laboratorio");

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel4.setText("Lote");

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel5.setText("Validade");

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 22)); // NOI18N
        jLabel7.setText("Observação");

        campoDescricao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        campoLaboratorio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        campoValidade.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        campoValidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValidadeActionPerformed(evt);
            }
        });

        campoLote.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        campoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoteActionPerformed(evt);
            }
        });

        campoObs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoObs))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(campoLote)
                    .addComponent(campoLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campoObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getAccessibleContext().setAccessibleName("Vacinas");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Vacinas vacinas = new Vacinas();
        vacinas.setVisible(true);
        vacinas.carregarTabela();
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // TODO add your handling code here:
        
        if (this.campoDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o nome daa Vacina!");
        } else if (this.campoLaboratorio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Laboratorio!");
            
        } else if(this.campoLote.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o lote");
            
        } else if (this.campoValidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a validade");
        } else if(!isDataValida()){
                
        }
        else{
            inserirCadastro();
            Vacinas vacinas = new Vacinas();
            vacinas.setVisible(true);
            vacinas.carregarTabela();
            this.dispose();
                   
           }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void campoValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacinas_Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacinas_Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacinas_Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacinas_Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacinas_Tela_Cadastro().setVisible(true);
            }
        });
    }
    
    public void inserirCadastro() {
        
        
        try {
            // Conecta ao banco de dados
            Connection con = Conexao.conector();
            // Monta a consulta SQL e prepara para executar
            String sql = "insert into vacina(vc_desc, vc_laboratorio, vc_lote, vc_validade, vc_obs) values (?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            
            String dataHora = campoValidade.getText();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
            Date dataFormatada = new SimpleDateFormat("dd/MM/yyyy").parse(dataHora);
            String dataBD = formato.format(dataFormatada);
            
            // Define os dados para inserir
            ps.setString(1, campoDescricao.getText());
            ps.setString(2, campoLaboratorio.getText());
            ps.setString(3, campoLote.getText());
            ps.setString(4, dataBD);
            ps.setString(5, campoObs.getText());
            // Executa a acao para inserir o registro no banco
            ps.executeUpdate();
            // Mensagem de confirmacao do cadastro
            JOptionPane.showMessageDialog(null, "Vacina cadastrada com sucesso!");
            // Limpa campos
            //campoID.setText("");
            campoDescricao.setText("");
            campoLote.setText("");
            campoValidade.setText("");
            campoObs.setText("");
            // Finaliza conexao
            ps.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro!", "Erro", JOptionPane.ERROR_MESSAGE);
            System.out.println("Erro ao inserir registro: " + e);
        }
    }
    
       public boolean dataHoraValida(String dataHora) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/uuuu").withResolverStyle(ResolverStyle.STRICT);
            LocalDate d = LocalDate.parse(dataHora, formatter);
            System.out.println("Data/Hora valida: " + dataHora);
            return true;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Data/Hora invalida: " + dataHora);
            return false;
        }
    }
        
    public boolean isDataValida() {
        boolean valido = false;
        String dataHora = campoValidade.getText();
        if (!dataHoraValida(dataHora)) {
            JOptionPane.showMessageDialog(null, "Informe uma data e hora válida!");
        } else {
            valido = true;
        }
        return valido;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoLaboratorio;
    private javax.swing.JTextField campoLote;
    private javax.swing.JTextField campoObs;
    private javax.swing.JTextField campoValidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
